version: "3"

services:
  web:
    build: .
    command: ./wait-for-it.sh postgres:5432 --strict --timeout=0 -- ./wait-for-it.sh redis:6379 --strict --timeout=0 -- bash -c "PORT=8000 bash dokku-boot.sh"
    volumes:
      - .:/app
      - .ssh:/root/.ssh
    ports:
      - 8000:8000
    env_file:
      - .env
    depends_on:
      - postgres
      - redis
    env_file:
      - .env
  celery:
    build: .
    command: ./wait-for-it.sh postgres:5432 --strict --timeout=0 -- ./wait-for-it.sh redis:6379 --strict --timeout=0 -- bash -c "python manage.py celery"
    volumes:
      - .:/app
      - .ssh:/root/.ssh
    environment:
      - DATABASE_URL=postgres://postgres:example@postgres:5432/wharf
      - BROKER_URL=redis://redis:6379/0
      - CACHE_URL=redis://redis:6379/1
      - DOKKU_SSH_HOST=${DOKKU_SSH_HOST:-127.0.0.1}
      - DOKKU_SSH_PORT=${DOKKU_SSH_PORT:-22}
    depends_on:
      - postgres
      - redis
    env_file:
      - .env

  postgres:
    image: postgres:10-alpine
    environment:
      POSTGRES_DB: wharf
      POSTGRES_PASSWORD: example
    env_file:
      - .env
  redis:
    image: redis:4-alpine
    env_file:
      - .env